<?php

namespace Database\Seeders;

use App\Models\Opportunity;
use Illuminate\Database\Seeder;

class OpportunitySeeder extends Seeder
{
    public function run(): void
    {
        $data = $this->getOpportunitiesData();

        foreach ($data as $item) {
            Opportunity::withoutGlobalScopes()->updateOrCreate(
                [
                    'title' => $item['title'],
                    'external_url' => $item['external_url'],
                ],
                [
                    'description' => $item['description'],
                    'funding_type' => $this->normalizeFundingType($item['funding_type']),
                    'deadline' => $item['deadline'],
                    'funding_min' => (float) $item['funding_min'],
                    'funding_max' => (float) $item['funding_max'],
                    'status' => $item['status'] ?? 'active',
                    'external_url' => $item['external_url'],
                    'source' => $item['source'],
                ]
            );
        }
    }

    protected function normalizeFundingType(string $type): string
    {
        $lower = strtolower($type);
        if (str_contains($lower, 'equity') && ! str_contains($lower, 'equity-free')) {
            return 'equity';
        }
        if (str_contains($lower, 'debt') || str_contains($lower, 'loan')) {
            return 'debt';
        }
        if (str_contains($lower, 'prize') || str_contains($lower, 'cash prize') || str_contains($lower, 'competition')) {
            return 'prize';
        }
        return 'grant';
    }

    protected function getOpportunitiesData(): array
    {
        return [
            ['title' => 'Tony Elumelu Foundation Entrepreneurship Programme 2026', 'description' => 'Programme phare de mentorat et de financement pour les entrepreneurs africains dans tous les secteurs tech (Agritech, Fintech, etc.).', 'funding_type' => 'Seed Grant', 'deadline' => '2026-03-01', 'funding_min' => 5000.00, 'funding_max' => 5000.00, 'status' => 'active', 'external_url' => 'https://www.tefconnect.net/', 'source' => 'Tony Elumelu Foundation'],
            ['title' => 'Mastercard Foundation EdTech Fellowship 2026 - MEST Africa', 'description' => 'Accélérateur dédié aux startups EdTech au Ghana, offrant un soutien financier et technique pour améliorer les résultats d\'apprentissage.', 'funding_type' => 'Equity-free Grant', 'deadline' => '2026-04-15', 'funding_min' => 60000.00, 'funding_max' => 60000.00, 'status' => 'active', 'external_url' => 'https://melwater-me.st/edtech', 'source' => 'MEST Africa'],
            ['title' => 'Common Fund for Commodities (CFC) - 2026 Call for Proposals', 'description' => 'Appel à projets ciblant l\'agriculture intelligente face au climat et les innovations agritech IoT/Hardware.', 'funding_type' => 'Grant/Loan', 'deadline' => '2026-04-01', 'funding_min' => 50000.00, 'funding_max' => 300000.00, 'status' => 'active', 'external_url' => 'https://www.common-fund.org/', 'source' => 'CFC International'],
            ['title' => 'Next Startupper Award 2026', 'description' => 'Concours pour jeunes entrepreneurs développant des solutions technologiques à fort impact social ou environnemental.', 'funding_type' => 'Grant', 'deadline' => '2026-03-09', 'funding_min' => 5000.00, 'funding_max' => 5000.00, 'status' => 'active', 'external_url' => 'https://startupper.totalenergies.com/', 'source' => 'TotalEnergies'],
            ['title' => 'Connect NextGen Hackathon Nigeria 2026', 'description' => 'Hackathon et accélération pour startups nigérianes en Agritech, Edtech et IoT.', 'funding_type' => 'Equity-free Funding', 'deadline' => '2026-03-10', 'funding_min' => 10000.00, 'funding_max' => 25000.00, 'status' => 'active', 'external_url' => 'https://techrevolutionafrica.com/nextgen', 'source' => 'Ericsson / Tech Revolution Africa'],
            ['title' => 'Global Health EDCTP3 Grants 2026', 'description' => 'Financement massif pour les innovateurs Healthtech luttant contre les maladies infectieuses et liées au climat en Afrique.', 'funding_type' => 'Research Grant', 'deadline' => '2026-03-04', 'funding_min' => 100000.00, 'funding_max' => 500000.00, 'status' => 'active', 'external_url' => 'https://www.edctp.org/', 'source' => 'EU-Africa Partnership'],
            ['title' => 'Agri-Business Facility (ABF) Window 2 - 2026', 'description' => 'Matching grant pour les entreprises de transformation et producteurs utilisant la tech pour réduire les pertes post-récolte.', 'funding_type' => 'Matching Grant', 'deadline' => '2026-05-31', 'funding_min' => 20000.00, 'funding_max' => 150000.00, 'status' => 'active', 'external_url' => 'https://www.agribusiness-facility.org/', 'source' => 'GIZ'],
            ['title' => 'BlueInvest Africa 2026 - South Africa', 'description' => 'Opportunité pour les startups de l\'économie bleue (aquaculture intelligente, logistique maritime tech).', 'funding_type' => 'Investment/Grant', 'deadline' => '2026-03-15', 'funding_min' => 10000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://vc4a.com/blue-invest/', 'source' => 'European Commission'],
            ['title' => 'Challenge App Afrique 2026 - RFI/France24', 'description' => 'Concours pour entrepreneurs francophones : \'La tech au service d\'un monde propre\' (Greentech/Agritech).', 'funding_type' => 'Grant', 'deadline' => '2026-02-28', 'funding_min' => 15000.00, 'funding_max' => 15000.00, 'status' => 'active', 'external_url' => 'https://appafrique.rfi.fr/', 'source' => 'RFI'],
            ['title' => 'Accelerate Africa Cohort 2026', 'description' => 'Programme de 12 semaines pour startups à fort potentiel avec accès au capital de Future Africa.', 'funding_type' => 'Equity Investment', 'deadline' => '2026-03-30', 'funding_min' => 50000.00, 'funding_max' => 500000.00, 'status' => 'active', 'external_url' => 'https://www.accelerateafrica.com/', 'source' => 'Future Africa'],
            ['title' => 'Antler Nairobi 2026 Program', 'description' => 'Financement pré-amorçage pour les fondateurs tech au Kenya (tous secteurs).', 'funding_type' => 'Equity', 'deadline' => '2026-03-15', 'funding_min' => 100000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://www.antler.co/location/nairobi', 'source' => 'Antler'],
            ['title' => 'Renew Capital Venture Lab 2026', 'description' => 'Soutien aux startups tech-enabled à travers l\'Afrique avec un focus sur l\'impact.', 'funding_type' => 'Equity/Convertible', 'deadline' => '2026-06-30', 'funding_min' => 50000.00, 'funding_max' => 300000.00, 'status' => 'active', 'external_url' => 'https://www.renewcapital.com/', 'source' => 'Renew Capital'],
            ['title' => 'GITEX Africa Supernova Challenge 2026', 'description' => 'Pitch competition à Marrakech pour les meilleures startups du continent.', 'funding_type' => 'Cash Prize', 'deadline' => '2026-03-01', 'funding_min' => 10000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://www.gitexafrica.com/', 'source' => 'GITEX Africa'],
            ['title' => 'Katapult Africa Accelerator 2026', 'description' => 'Accélérateur pour Agritech et Climate Tech avec un ticket d\'investissement significatif.', 'funding_type' => 'Equity', 'deadline' => '2026-04-30', 'funding_min' => 150000.00, 'funding_max' => 400000.00, 'status' => 'active', 'external_url' => 'https://katapult.vc/africa/', 'source' => 'Katapult'],
            ['title' => 'AI4Good AgriTech Farmer Solutions 2026', 'description' => 'Subvention pour le déploiement de l\'intelligence artificielle au service des petits agriculteurs.', 'funding_type' => 'Grant', 'deadline' => '2026-05-20', 'funding_min' => 50000.00, 'funding_max' => 360000.00, 'status' => 'active', 'external_url' => 'https://www.ictworks.org/funding', 'source' => 'ICTworks'],
            ['title' => 'Google for Startups Accelerator: Africa 2026', 'description' => 'Accélération sans prise de participation pour startups utilisant le Cloud et l\'IA.', 'funding_type' => 'Equity-free Support', 'deadline' => '2026-05-15', 'funding_min' => 0.00, 'funding_max' => 200000.00, 'status' => 'active', 'external_url' => 'https://startup.google.com/accelerator/africa/', 'source' => 'Google'],
            ['title' => 'Visa Accelerator Program Africa 2026', 'description' => 'Support pour les startups Fintech et de paiement en phase de croissance.', 'funding_type' => 'Equity/Partnership', 'deadline' => '2026-04-10', 'funding_min' => 50000.00, 'funding_max' => 250000.00, 'status' => 'active', 'external_url' => 'https://africa.visa.com/visa-everywhere/innovation-program.html', 'source' => 'Visa'],
            ['title' => 'Orange Summer Challenge 2026', 'description' => 'Concours pour jeunes innovateurs (Edtech/IoT) dans les pays Orange en Afrique.', 'funding_type' => 'Grant/Prize', 'deadline' => '2026-06-30', 'funding_min' => 2000.00, 'funding_max' => 10000.00, 'status' => 'active', 'external_url' => 'https://www.orange.com/en/orange-digital-center', 'source' => 'Orange Middle East & Africa'],
            ['title' => 'Afreximbank CANEX Prize for Creative Tech 2026', 'description' => 'Soutien aux technologies appliquées aux industries créatives en Afrique.', 'funding_type' => 'Grant', 'deadline' => '2026-07-15', 'funding_min' => 5000.00, 'funding_max' => 20000.00, 'status' => 'active', 'external_url' => 'https://canex.africa/', 'source' => 'Afreximbank'],
            ['title' => 'Bayer Foundation Women Empowerment Award 2026', 'description' => 'Prix pour les femmes entrepreneures en Afrique dans la santé et l\'agriculture.', 'funding_type' => 'Grant', 'deadline' => '2026-03-31', 'funding_min' => 25000.00, 'funding_max' => 25000.00, 'status' => 'active', 'external_url' => 'https://www.bayer-foundation.com/', 'source' => 'Bayer Foundation'],
            ['title' => 'Grameen Foundation Agritech Grant 2026', 'description' => 'Financement pour solutions numériques améliorant la résilience climatique des femmes agricultrices.', 'funding_type' => 'Grant', 'deadline' => '2026-04-22', 'funding_min' => 10000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://grameenfoundation.org/', 'source' => 'Grameen Foundation'],
            ['title' => 'Baobab Network Accelerator 2026', 'description' => 'Investissement initial pour startups tech africaines early-stage.', 'funding_type' => 'Equity', 'deadline' => '2026-03-31', 'funding_min' => 50000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://thebaobabnetwork.com/', 'source' => 'The Baobab Network'],
            ['title' => 'WFP Innovation Challenge 2026', 'description' => 'Solutions tech pour lutter contre la faim (Agritech/Logistique) en Afrique de l\'Ouest et de l\'Est.', 'funding_type' => 'Grant', 'deadline' => '2026-05-05', 'funding_min' => 100000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://innovation.wfp.org/', 'source' => 'World Food Programme'],
            ['title' => 'Standard Chartered Women in Tech Senegal 2026', 'description' => 'Incubateur pour femmes fondatrices de startups technologiques au Sénégal.', 'funding_type' => 'Grant', 'deadline' => '2026-04-15', 'funding_min' => 10000.00, 'funding_max' => 10000.00, 'status' => 'active', 'external_url' => 'https://www.sc.com/sn/', 'source' => 'Standard Chartered'],
            ['title' => 'Villgro Africa Healthtech Call 2026', 'description' => 'Incubation et investissement pour dispositifs médicaux et solutions de santé numérique.', 'funding_type' => 'Grant/Equity', 'deadline' => '2026-06-01', 'funding_min' => 20000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://villgroafrica.org/', 'source' => 'Villgro Africa'],
            ['title' => 'Digital Energy Challenge 2026', 'description' => 'Pour les startups développant des solutions numériques pour l\'accès à l\'énergie en Afrique.', 'funding_type' => 'Grant', 'deadline' => '2026-05-15', 'funding_min' => 150000.00, 'funding_max' => 150000.00, 'status' => 'active', 'external_url' => 'https://www.afd.fr/en/digital-energy-challenge', 'source' => 'AFD'],
            ['title' => 'Savannah VC Early-Stage Fund 2026', 'description' => 'Capital d\'amorçage pour startups SaaS et Fintech opérant au Kenya et Nigeria.', 'funding_type' => 'Equity', 'deadline' => '2026-08-30', 'funding_min' => 25000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://savannah.vc/', 'source' => 'Savannah Fund'],
            ['title' => 'Fondation l\'Oréal - For Women in Science Africa 2026', 'description' => 'Bourses pour chercheuses utilisant l\'IA ou la biotechnologie pour le développement.', 'funding_type' => 'Grant', 'deadline' => '2026-03-31', 'funding_min' => 10000.00, 'funding_max' => 15000.00, 'status' => 'active', 'external_url' => 'https://www.forwomeninscience.com/', 'source' => 'L\'Oréal Foundation'],
            ['title' => 'MEST Express Accelerator 2026', 'description' => 'Accélération pour startups ghanéennes prêtes pour l\'investissement.', 'funding_type' => 'Equity-free Grant', 'deadline' => '2026-04-20', 'funding_min' => 10000.00, 'funding_max' => 20000.00, 'status' => 'active', 'external_url' => 'https://melwater-me.st/express', 'source' => 'MEST Africa'],
            ['title' => 'UNICEF Startup Lab Ghana Cohort 6', 'description' => 'Soutien aux startups tech impactant les enfants (WASH, Edtech, Health).', 'funding_type' => 'Grant', 'deadline' => '2026-02-20', 'funding_min' => 6000.00, 'funding_max' => 15000.00, 'status' => 'active', 'external_url' => 'https://www.unicef.org/ghana/startup-lab', 'source' => 'UNICEF'],
            ['title' => 'GSMA Innovation Fund for Climate Resilience 2026', 'description' => 'Financement pour solutions mobiles luttant contre les changements climatiques.', 'funding_type' => 'Grant', 'deadline' => '2026-05-15', 'funding_min' => 100000.00, 'funding_max' => 250000.00, 'status' => 'active', 'external_url' => 'https://www.gsma.com/innovation-fund/', 'source' => 'GSMA'],
            ['title' => 'Catalytic Africa - Co-investment Fund 2026', 'description' => 'Fonds de co-investissement pour Business Angels investissant dans des startups africaines.', 'funding_type' => 'Matching Investment', 'deadline' => '2026-12-31', 'funding_min' => 10000.00, 'funding_max' => 60000.00, 'status' => 'active', 'external_url' => 'https://catalytic-africa.com/', 'source' => 'ABAN / AfriLabs'],
            ['title' => 'Growth Africa Accelerator 2026', 'description' => 'Accélération commerciale pour PME tech en Éthiopie, Kenya, Ouganda et Zambie.', 'funding_type' => 'Advisory/Support', 'deadline' => '2026-03-31', 'funding_min' => 0.00, 'funding_max' => 0.00, 'status' => 'active', 'external_url' => 'https://growthafrica.com/', 'source' => 'GrowthAfrica'],
            ['title' => 'Jack Ma Foundation - Africa\'s Business Heroes 2026', 'description' => 'Concours panafricain pour tous secteurs, prix cash important.', 'funding_type' => 'Grant', 'deadline' => '2026-05-12', 'funding_min' => 10000.00, 'funding_max' => 300000.00, 'status' => 'active', 'external_url' => 'https://africabusinessheroes.org/', 'source' => 'Jack Ma Foundation'],
            ['title' => 'Norrsken Accelerator 2026 - Rwanda', 'description' => 'Investissement et accélération à Kigali pour startups à impact mondial.', 'funding_type' => 'Equity', 'deadline' => '2026-04-15', 'funding_min' => 125000.00, 'funding_max' => 125000.00, 'status' => 'active', 'external_url' => 'https://www.norrsken.org/accelerator', 'source' => 'Norrsken Foundation'],
            ['title' => 'Y Combinator Summer 2026 - Africa Focus', 'description' => 'Le célèbre accélérateur US finance de plus en plus de startups africaines early-stage.', 'funding_type' => 'Equity', 'deadline' => '2026-03-24', 'funding_min' => 500000.00, 'funding_max' => 500000.00, 'status' => 'active', 'external_url' => 'https://www.ycombinator.com/apply', 'source' => 'Y Combinator'],
            ['title' => 'Africa Tech Summit Nairobi - Pitch Live 2026', 'description' => 'Opportunité de pitcher devant des VC internationaux au Kenya.', 'funding_type' => 'Investment Access', 'deadline' => '2026-04-01', 'funding_min' => 0.00, 'funding_max' => 0.00, 'status' => 'active', 'external_url' => 'https://www.africatechsummit.com/nairobi/', 'source' => 'Africa Tech Summit'],
            ['title' => 'HealthTech Hub Africa Accelerator 2026', 'description' => 'Soutien aux startups de santé publique basées au Rwanda et opérant en Afrique.', 'funding_type' => 'Grant/Equity', 'deadline' => '2026-05-30', 'funding_min' => 30000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://thehealthtechhub.africa/', 'source' => 'Novartis Foundation'],
            ['title' => 'D-Prize Distribution Challenge 2026', 'description' => 'Capital d\'amorçage pour de nouvelles organisations distribuant des techs de santé/agri.', 'funding_type' => 'Seed Grant', 'deadline' => '2026-05-11', 'funding_min' => 5000.00, 'funding_max' => 20000.00, 'status' => 'active', 'external_url' => 'https://d-prize.org/', 'source' => 'D-Prize'],
            ['title' => 'Fondation Merieux - Small Grants 2026', 'description' => 'Soutien aux petits projets Healthtech locaux en Afrique francophone.', 'funding_type' => 'Grant', 'deadline' => '2026-03-31', 'funding_min' => 5000.00, 'funding_max' => 5000.00, 'status' => 'active', 'external_url' => 'https://www.fondation-merieux.org/', 'source' => 'Fondation Merieux'],
            ['title' => 'African Development Bank - Fashionomics Accelerator 2026', 'description' => 'Tech appliquée à la mode et au textile (E-commerce, Supply Chain).', 'funding_type' => 'Grant', 'deadline' => '2026-06-25', 'funding_min' => 5000.00, 'funding_max' => 10000.00, 'status' => 'active', 'external_url' => 'https://fashionomicsafrica.org/', 'source' => 'AfDB'],
            ['title' => 'Microsoft for Startups Founders Hub 2026', 'description' => 'Crédits Azure et support technique pour startups africaines cloud-native.', 'funding_type' => 'Credits/Support', 'deadline' => '2026-12-31', 'funding_min' => 1000.00, 'funding_max' => 150000.00, 'status' => 'active', 'external_url' => 'https://foundershub.startups.microsoft.com/', 'source' => 'Microsoft'],
            ['title' => 'SAIS Agritech Accelerator 2026', 'description' => 'Programme de préparation à l\'investissement pour startups Agritech en Afrique australe et de l\'Est.', 'funding_type' => 'Grant/Investment', 'deadline' => '2026-04-10', 'funding_min' => 10000.00, 'funding_max' => 40000.00, 'status' => 'active', 'external_url' => 'https://vc4a.com/giz/sais-2026/', 'source' => 'GIZ / SAIS'],
            ['title' => 'Seedstars World Competition 2026', 'description' => 'Compétition mondiale pour startups tech des marchés émergents.', 'funding_type' => 'Equity', 'deadline' => '2026-07-01', 'funding_min' => 50000.00, 'funding_max' => 500000.00, 'status' => 'active', 'external_url' => 'https://www.seedstarsworld.com/', 'source' => 'Seedstars'],
            ['title' => 'IFA - African Agriculture Innovation Prize 2026', 'description' => 'Récompense pour les technologies améliorant la nutrition et la sécurité alimentaire.', 'funding_type' => 'Grant', 'deadline' => '2026-05-15', 'funding_min' => 10000.00, 'funding_max' => 25000.00, 'status' => 'active', 'external_url' => 'https://www.fertilizer.org/', 'source' => 'International Fertilizer Association'],
            ['title' => 'Standard Bank - Fintech Incubator 2026', 'description' => 'Pour startups Fintech en Afrique du Sud et pays limitrophes.', 'funding_type' => 'Seed Funding', 'deadline' => '2026-04-30', 'funding_min' => 20000.00, 'funding_max' => 100000.00, 'status' => 'active', 'external_url' => 'https://www.standardbank.com/', 'source' => 'Standard Bank'],
            ['title' => 'Injini EdTech Accelerator 2026', 'description' => 'Accélérateur spécialisé Edtech pour l\'Afrique subsaharienne, basé au Cap.', 'funding_type' => 'Equity-free Grant', 'deadline' => '2026-05-20', 'funding_min' => 10000.00, 'funding_max' => 30000.00, 'status' => 'active', 'external_url' => 'https://www.injini.africa/', 'source' => 'Injini'],
            ['title' => 'Founders Factory Africa - Build Program 2026', 'description' => 'Co-création et investissement pour startups Fintech et Healthtech.', 'funding_type' => 'Equity', 'deadline' => '2026-09-01', 'funding_min' => 100000.00, 'funding_max' => 250000.00, 'status' => 'active', 'external_url' => 'https://www.foundersfactory.africa/', 'source' => 'Founders Factory Africa'],
            ['title' => 'Africa Online Education Grant 2026', 'description' => 'Subvention pour plateformes d\'apprentissage en ligne accessibles hors-ligne.', 'funding_type' => 'Grant', 'deadline' => '2026-03-29', 'funding_min' => 5000.00, 'funding_max' => 20000.00, 'status' => 'active', 'external_url' => 'https://www.fundsforngos.org/', 'source' => 'Global Education Fund'],
            ['title' => 'MEST Training Program 2026 Class', 'description' => 'Formation intensive d\'un an et financement pour futurs entrepreneurs tech.', 'funding_type' => 'Equity-free Training', 'deadline' => '2026-05-15', 'funding_min' => 0.00, 'funding_max' => 0.00, 'status' => 'active', 'external_url' => 'https://melwater-me.st/', 'source' => 'MEST'],
            ['title' => 'She Loves Tech Africa 2026', 'description' => 'Concours de startups pour femmes fondatrices ou tech bénéficiant aux femmes.', 'funding_type' => 'Grant/Investment', 'deadline' => '2026-06-15', 'funding_min' => 5000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://www.shelovestech.org/', 'source' => 'She Loves Tech'],
            ['title' => 'E-Voucher Grant - Green Tech Senegal 2026', 'description' => 'Aide financière pour l\'adoption de technologies vertes par les PME sénégalaises.', 'funding_type' => 'Grant', 'deadline' => '2026-04-10', 'funding_min' => 5000.00, 'funding_max' => 15000.00, 'status' => 'active', 'external_url' => 'https://www.giz.de/en/worldwide/335.html', 'source' => 'GIZ Senegal'],
            ['title' => 'Startup Tunisia - Flywheel Program 2026', 'description' => 'Subventions pour startups labellisées en phase d\'amorçage ou d\'accélération.', 'funding_type' => 'Grant', 'deadline' => '2026-12-31', 'funding_min' => 5000.00, 'funding_max' => 60000.00, 'status' => 'active', 'external_url' => 'https://startup.smartcapital.tn/', 'source' => 'Smart Capital Tunisia'],
            ['title' => 'Africa Fertilizer Financing Mechanism (AFFM) 2026', 'description' => 'Support aux startups Agritech facilitant l\'accès aux intrants.', 'funding_type' => 'Loan/Guarantee', 'deadline' => '2026-06-15', 'funding_min' => 100000.00, 'funding_max' => 1000000.00, 'status' => 'active', 'external_url' => 'https://www.afdb.org/en/affm', 'source' => 'AfDB'],
            ['title' => 'Civic Tech Innovation Fund 2026', 'description' => 'Solutions numériques pour la gouvernance et la participation citoyenne en Afrique.', 'funding_type' => 'Grant', 'deadline' => '2026-03-31', 'funding_min' => 10000.00, 'funding_max' => 40000.00, 'status' => 'active', 'external_url' => 'https://civictech.africa/', 'source' => 'Civic Tech Innovation Network'],
            ['title' => 'GoGettaz Agripreneur Prize 2026', 'description' => 'Concours continental pour jeunes entrepreneurs dans l\'agrifood tech.', 'funding_type' => 'Grant', 'deadline' => '2026-06-15', 'funding_min' => 50000.00, 'funding_max' => 50000.00, 'status' => 'active', 'external_url' => 'https://gogettaz.africa/', 'source' => 'Generation Africa'],
            ['title' => 'AfriLabs Capacity Building Awards 2026', 'description' => 'Financement pour hubs technologiques et incubateurs africains.', 'funding_type' => 'Grant', 'deadline' => '2026-05-15', 'funding_min' => 5000.00, 'funding_max' => 15000.00, 'status' => 'active', 'external_url' => 'https://www.afrilabs.com/', 'source' => 'AfriLabs'],
            ['title' => 'Women in Fintech Hackathon 2026 - Uganda', 'description' => 'Compétition de développement de solutions financières inclusives par des femmes.', 'funding_type' => 'Grant', 'deadline' => '2026-08-10', 'funding_min' => 1000.00, 'funding_max' => 5000.00, 'status' => 'active', 'external_url' => 'https://www.hi-pipo.com/', 'source' => 'HiPipo'],
            ['title' => 'JICA Ninja Business Plan Competition 2026', 'description' => 'Soutien aux startups tech résolvant des problèmes sociaux complexes en Afrique.', 'funding_type' => 'Equity/Grant', 'deadline' => '2026-04-15', 'funding_min' => 30000.00, 'funding_max' => 30000.00, 'status' => 'active', 'external_url' => 'https://www.jica.go.jp/english/', 'source' => 'JICA'],
            ['title' => 'Climate Launchpad Africa 2026', 'description' => 'Le plus grand concours mondial de business ideas en CleanTech/Greentech.', 'funding_type' => 'Grant/Prize', 'deadline' => '2026-06-01', 'funding_min' => 2500.00, 'funding_max' => 10000.00, 'status' => 'active', 'external_url' => 'https://climatelaunchpad.org/', 'source' => 'EIT Climate-KIC'],
        ];
    }
}
